# Generated by Django 2.1.7 on 2019-04-02 04:24

from django.db import migrations, models
import django.db.models.deletion
import systems.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subnet', '0001_initial'),
        ('firewall', '0001_initial'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('config', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('provider_type', models.CharField(editable=False, max_length=128, null=True)),
                ('variables', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('state_config', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('public_ip', models.CharField(max_length=128, null=True)),
                ('private_ip', models.CharField(max_length=128, null=True)),
                ('user', models.CharField(max_length=128, null=True)),
                ('password', systems.models.fields.EncryptedCharField(max_length=1096, null=True)),
                ('private_key', systems.models.fields.EncryptedDataField(null=True)),
                ('data_device', models.CharField(max_length=256, null=True)),
                ('backup_device', models.CharField(max_length=256, null=True)),
                ('firewalls', models.ManyToManyField(editable=False, related_name='server_relation', to='firewall.Firewall')),
                ('groups', models.ManyToManyField(related_name='server_relation', to='group.Group')),
                ('subnet', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='server_relation', to='subnet.Subnet')),
            ],
            options={
                'verbose_name': 'server',
                'verbose_name_plural': 'servers',
                'db_table': 'cluster_server',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together={('subnet', 'name')},
        ),
    ]
