# Generated by Django 2.2 on 2019-04-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='firewalls',
            field=models.ManyToManyField(editable=False, related_name='server_relations', to='firewall.Firewall'),
        ),
        migrations.AlterField(
            model_name='server',
            name='groups',
            field=models.ManyToManyField(related_name='server_relations', to='group.Group'),
        ),
    ]
