# Generated by Django 2.2 on 2019-04-08 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('load_balancer', '0003_auto_20190406_2145'),
        ('server', '0002_auto_20190406_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='load_balancer',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='server_relation', to='load_balancer.LoadBalancer'),
        ),
    ]
