# Generated by Django 2.1.7 on 2019-04-02 00:43

from django.db import migrations, models
import django.db.models.deletion
import systems.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subnet', '0002_auto_20190401_2043'),
        ('server', '0002_auto_20190313_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['name'], 'verbose_name': 'server', 'verbose_name_plural': 'servers'},
        ),
        migrations.AddField(
            model_name='server',
            name='provider_type',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='config',
            field=systems.models.fields.EncryptedDataField(default={}, editable=False),
        ),
        migrations.AlterField(
            model_name='server',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='firewalls',
            field=models.ManyToManyField(editable=False, related_name='server_relation', to='firewall.Firewall'),
        ),
        migrations.AlterField(
            model_name='server',
            name='id',
            field=models.CharField(editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='server',
            name='state_config',
            field=systems.models.fields.EncryptedDataField(default={}, editable=False),
        ),
        migrations.AlterField(
            model_name='server',
            name='subnet',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='server_relation', to='subnet.Subnet'),
        ),
        migrations.AlterField(
            model_name='server',
            name='updated',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='variables',
            field=systems.models.fields.EncryptedDataField(default={}, editable=False),
        ),
        migrations.RemoveField(
            model_name='server',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='server',
            name='type',
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together={('subnet', 'name')},
        ),
    ]
