# Generated by Django 2.2 on 2019-04-08 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('load_balancer_listener', '0002_remove_loadbalancerlistener_domain'),
        ('server', '0003_server_load_balancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='load_balancer_listener',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='server_relation', to='load_balancer_listener.LoadBalancerListener'),
        ),
    ]
