# Generated by Django 2.2 on 2019-04-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_server_load_balancer_listener'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='ssh_port',
            field=models.IntegerField(default=22),
        ),
    ]
