# Generated by Django 2.2 on 2019-05-20 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0006_auto_20190406_2145'),
        ('server', '0006_auto_20190513_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='domain',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='server_relation', to='domain.Domain'),
        ),
        migrations.AddField(
            model_name='server',
            name='domain_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
