# Generated by Django 3.0 on 2020-05-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_balancer_listener', '0002_remove_loadbalancerlistener_domain'),
        ('server', '0007_auto_20190520_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='load_balancer_listener',
        ),
        migrations.AddField(
            model_name='server',
            name='load_balancer_listeners',
            field=models.ManyToManyField(editable=False, related_name='server_relations', to='load_balancer_listener.LoadBalancerListener'),
        ),
    ]
