# Generated by Django 3.2.5 on 2021-07-13 07:03

from django.db import migrations, models
import django.db.models.deletion
import systems.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerVolume',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('config', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('provider_type', models.CharField(editable=False, max_length=128, null=True)),
                ('variables', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('state_config', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('location', models.CharField(max_length=256)),
                ('type', models.CharField(default='ext4', max_length=128)),
                ('owner', models.CharField(default='root', max_length=128)),
                ('group', models.CharField(default='root', max_length=128)),
                ('mode', models.CharField(default='0755', max_length=25)),
                ('options', systems.models.fields.CSVField(null=True)),
                ('server', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servervolume_relation', to='server.server')),
            ],
            options={
                'verbose_name': 'server volume',
                'verbose_name_plural': 'server volumes',
                'db_table': 'cluster_server_volume',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('server', 'name')},
            },
        ),
    ]
