# Generated by Django 2.2 on 2019-05-14 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_volume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servervolume',
            name='path',
        ),
    ]
