# Generated by Django 2.2 on 2019-05-15 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_volume', '0002_remove_servervolume_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servervolume',
            old_name='source',
            new_name='location',
        ),
    ]
