# Generated by Django 3.0 on 2020-06-05 18:59

from django.db import migrations
import systems.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('server_volume', '0003_auto_20190515_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servervolume',
            name='options',
            field=systems.models.fields.CSVField(null=True),
        ),
    ]
