# Generated by Django 3.2.5 on 2021-07-13 07:03

from django.db import migrations, models
import django.db.models.deletion
import systems.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('config', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('provider_type', models.CharField(editable=False, max_length=128, null=True)),
                ('variables', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('state_config', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('cidr', models.CharField(max_length=128, null=True)),
                ('use_public_ip', models.BooleanField(default=True)),
                ('use_nat', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(related_name='subnet_relations', to='group.Group')),
                ('nat_subnet', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subnet_relation', to='subnet.subnet')),
                ('network', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subnet_relation', to='network.network')),
            ],
            options={
                'verbose_name': 'subnet',
                'verbose_name_plural': 'subnets',
                'db_table': 'cluster_subnet',
                'ordering': ['cidr'],
                'abstract': False,
                'unique_together': {('network', 'name')},
            },
        ),
    ]
