# Generated by Django 2.2 on 2019-05-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subnet', '0002_auto_20190406_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnet',
            name='nat_subnets',
            field=models.ManyToManyField(editable=False, related_name='subnet_relations', to='subnet.Subnet'),
        ),
        migrations.AddField(
            model_name='subnet',
            name='use_nat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subnet',
            name='use_public_ip',
            field=models.BooleanField(default=True),
        ),
    ]
