# Generated by Django 2.2 on 2019-05-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subnet', '0003_auto_20190526_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subnet',
            old_name='nat_subnets',
            new_name='subnets',
        ),
    ]
