# Generated by Django 2.1.7 on 2019-04-02 04:24

from django.db import migrations, models
import django.db.models.deletion
import systems.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subnet', '0001_initial'),
        ('firewall', '0001_initial'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageMount',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('config', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('provider_type', models.CharField(editable=False, max_length=128, null=True)),
                ('variables', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('state_config', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('remote_host', models.CharField(max_length=128, null=True)),
                ('remote_path', models.CharField(max_length=256, null=True)),
                ('mount_options', models.TextField(null=True)),
                ('firewalls', models.ManyToManyField(editable=False, related_name='storagemount_relation', to='firewall.Firewall')),
                ('storage', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='storagemount_relation', to='storage.Storage')),
                ('subnet', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storagemount_relation', to='subnet.Subnet')),
            ],
            options={
                'verbose_name': 'mount',
                'verbose_name_plural': 'mounts',
                'db_table': 'cluster_storage_mount',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='storagemount',
            unique_together={('storage', 'name'), ('subnet', 'name')},
        ),
    ]
