# Generated by Django 3.2.5 on 2021-07-13 07:03

from django.db import migrations, models
import django.db.models.deletion
import systems.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
        ('firewall', '0001_initial'),
        ('subnet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageMount',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('config', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('provider_type', models.CharField(editable=False, max_length=128, null=True)),
                ('variables', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('state_config', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('remote_host', models.CharField(max_length=128, null=True)),
                ('remote_path', models.CharField(max_length=256, null=True)),
                ('mount_options', models.TextField(null=True)),
                ('firewalls', models.ManyToManyField(related_name='storagemount_relations', to='firewall.Firewall')),
                ('storage', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storagemount_relation', to='storage.storage')),
                ('subnet', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storagemount_relation', to='subnet.subnet')),
            ],
            options={
                'verbose_name': 'storage mount',
                'verbose_name_plural': 'storage mounts',
                'db_table': 'cluster_storage_mount',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('subnet', 'name')},
            },
        ),
    ]
