# Generated by Django 2.2 on 2019-04-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_mount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagemount',
            name='firewalls',
            field=models.ManyToManyField(editable=False, related_name='storagemount_relations', to='firewall.Firewall'),
        ),
    ]
