# Generated by Django 2.1.7 on 2019-03-14 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subnet', '0001_initial'),
        ('storage_mount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagemount',
            name='subnet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storagemount_relation', to='subnet.Subnet'),
        ),
        migrations.AlterUniqueTogether(
            name='storagemount',
            unique_together={('environment', 'name')},
        ),
    ]
