# Generated by Django 2.2 on 2019-05-17 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subnet', '0002_auto_20190406_2145'),
        ('storage_mount', '0002_auto_20190406_2145'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storagemount',
            unique_together={('subnet', 'name')},
        ),
    ]
