# Generated by Django 3.0 on 2020-06-05 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0002_auto_20190406_2145'),
        ('storage', '0002_auto_20190406_2145'),
        ('storage_mount', '0003_auto_20190517_0048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storagemount',
            options={'ordering': ['name'], 'verbose_name': 'storage mount', 'verbose_name_plural': 'storage mounts'},
        ),
        migrations.AlterField(
            model_name='storagemount',
            name='firewalls',
            field=models.ManyToManyField(related_name='storagemount_relations', to='firewall.Firewall'),
        ),
        migrations.AlterField(
            model_name='storagemount',
            name='storage',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storagemount_relation', to='storage.Storage'),
        ),
    ]
