# Generated by Django 3.0 on 2020-06-29 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subnet', '0005_auto_20190526_1431'),
        ('storage_mount', '0005_auto_20200616_0757'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storagemount',
            unique_together={('subnet', 'name')},
        ),
    ]
