# Generated by Django 2.2 on 2019-04-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('load_balancer', '0003_auto_20190406_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loadbalancer',
            options={'ordering': ['name'], 'verbose_name': 'load balancer', 'verbose_name_plural': 'load balancers'},
        ),
    ]
