# Generated by Django 3.0 on 2020-06-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0002_auto_20190406_2145'),
        ('subnet', '0005_auto_20190526_1431'),
        ('load_balancer', '0005_loadbalancer_subnets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadbalancer',
            name='firewalls',
            field=models.ManyToManyField(related_name='loadbalancer_relations', to='firewall.Firewall'),
        ),
        migrations.AlterField(
            model_name='loadbalancer',
            name='subnets',
            field=models.ManyToManyField(related_name='loadbalancer_relations', to='subnet.Subnet'),
        ),
    ]
