# Generated by Django 3.0 on 2020-10-11 03:34

from django.db import migrations, models
import systems.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='database_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='user_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='user_password',
            field=systems.models.fields.EncryptedCharField(max_length=256, null=True),
        ),
    ]
