# Generated by Django 2.1.7 on 2019-03-14 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firewall', '0001_initial'),
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewall',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='firewall_relation', to='network.Network'),
        ),
        migrations.AlterUniqueTogether(
            name='firewall',
            unique_together={('network', 'name')},
        ),
    ]
