# Generated by Django 3.2.5 on 2021-07-13 07:03

from django.db import migrations, models
import django.db.models.deletion
import systems.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
        ('network_peering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkPeeringRelation',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('config', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('provider_type', models.CharField(editable=False, max_length=128, null=True)),
                ('variables', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('state_config', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('network1', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='networkpeeringrelation_relation1', to='network.network')),
                ('network2', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='networkpeeringrelation_relation2', to='network.network')),
                ('network_peering', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='networkpeeringrelation_relation', to='network_peering.networkpeering')),
            ],
            options={
                'verbose_name': 'network peering relation',
                'verbose_name_plural': 'network peering relations',
                'db_table': 'cluster_network_peering_relation',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('network_peering', 'name')},
            },
        ),
    ]
