# Generated by Django 2.2 on 2019-04-13 15:41

from django.db import migrations, models
import django.db.models.deletion
import systems.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0002_auto_20190406_2145'),
        ('network_peering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkPeeringRelation',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('config', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('provider_type', models.CharField(editable=False, max_length=128, null=True)),
                ('variables', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('state_config', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('destination', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='networkpeeringrelation_destination', to='network.Network')),
                ('network_peering', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='networkpeeringrelation_relation', to='network_peering.NetworkPeering')),
                ('source', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='networkpeeringrelation_source', to='network.Network')),
            ],
            options={
                'verbose_name': 'network peering relation',
                'verbose_name_plural': 'network peering relations',
                'db_table': 'cluster_network_peering_relation',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('network_peering', 'name')},
            },
        ),
    ]
