# Generated by Django 2.2 on 2019-04-13 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20190406_2145'),
        ('network_peering_relation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkpeeringrelation',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='networkpeeringrelation',
            name='source',
        ),
        migrations.AddField(
            model_name='networkpeeringrelation',
            name='network1',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='networkpeeringrelation_relation1', to='network.Network'),
        ),
        migrations.AddField(
            model_name='networkpeeringrelation',
            name='network2',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='networkpeeringrelation_relation2', to='network.Network'),
        ),
    ]
