# Generated by Django 2.1.7 on 2019-03-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
        ('federation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='federation',
            name='networks',
            field=models.ManyToManyField(related_name='federation_relation', to='network.Network'),
        ),
        migrations.AlterUniqueTogether(
            name='federation',
            unique_together={('environment', 'name')},
        ),
    ]
