# Generated by Django 3.2.5 on 2021-07-13 07:03

from django.db import migrations, models
import systems.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkPeering',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('config', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('provider_type', models.CharField(editable=False, max_length=128, null=True)),
                ('variables', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('state_config', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('networks', models.ManyToManyField(related_name='networkpeering_relations', to='network.Network')),
            ],
            options={
                'verbose_name': 'network peering',
                'verbose_name_plural': 'network peerings',
                'db_table': 'cluster_network_peering',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
