# Generated by Django 2.2 on 2019-04-13 15:41

from django.db import migrations, models
import django.db.models.deletion
import systems.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0002_auto_20190406_2145'),
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkPeering',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('config', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('provider_type', models.CharField(editable=False, max_length=128, null=True)),
                ('variables', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('state_config', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('environment', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='networkpeering_relation', to='environment.Environment')),
                ('networks', models.ManyToManyField(editable=False, related_name='networkpeering_relations', to='network.Network')),
            ],
            options={
                'verbose_name': 'network peering',
                'verbose_name_plural': 'network peerings',
                'db_table': 'cluster_network_peering',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('environment', 'name')},
            },
        ),
    ]
