# Generated by Django 3.0 on 2020-06-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20190406_2145'),
        ('network_peering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkpeering',
            name='networks',
            field=models.ManyToManyField(related_name='networkpeering_relations', to='network.Network'),
        ),
    ]
