# Generated by Django 3.2.4 on 2021-07-11 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_peering', '0002_auto_20200605_1459'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='networkpeering',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='networkpeering',
            name='environment',
        ),
    ]
