# Generated by Django 2.1.7 on 2019-04-02 04:24

from django.db import migrations, models
import django.db.models.deletion
import systems.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainRecord',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('config', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('provider_type', models.CharField(editable=False, max_length=128, null=True)),
                ('variables', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('state_config', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('type', models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CAA', 'CAA'), ('CNAME', 'CNAME'), ('MX', 'MX'), ('NAPTR', 'NAPTR'), ('NS', 'NS'), ('PTR', 'PTR'), ('SOA', 'SOA'), ('SPF', 'SPF'), ('SRV', 'SRV'), ('TXT', 'TXT')], default='A', max_length=10)),
                ('ttl', models.IntegerField(default=300)),
                ('values', systems.models.fields.EncryptedDataField(default=[])),
                ('domain', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domainrecord_relation', to='domain.Domain')),
            ],
            options={
                'verbose_name': 'domain record',
                'verbose_name_plural': 'domain records',
                'db_table': 'cluster_domain_record',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='domainrecord',
            unique_together={('domain', 'name')},
        ),
    ]
