# Generated by Django 2.1.7 on 2019-04-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainrecord',
            name='target',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
