# Generated by Django 2.2 on 2019-04-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_certificate_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='groups',
            field=models.ManyToManyField(related_name='certificate_relations', to='group.Group'),
        ),
    ]
