# Generated by Django 2.1.7 on 2019-04-02 04:24

from django.db import migrations, models
import django.db.models.deletion
import systems.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firewall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('config', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('provider_type', models.CharField(editable=False, max_length=128, null=True)),
                ('variables', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('state_config', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('mode', models.CharField(choices=[('ingress', 'ingress'), ('egress', 'egress')], default='ingress', max_length=10)),
                ('from_port', models.IntegerField(null=True)),
                ('to_port', models.IntegerField(null=True)),
                ('protocol', models.CharField(choices=[('tcp', 'tcp'), ('udp', 'udp'), ('icmp', 'icmp')], default='tcp', max_length=10)),
                ('cidrs', systems.models.fields.CSVField(null=True)),
                ('firewall', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='firewallrule_relation', to='firewall.Firewall')),
            ],
            options={
                'verbose_name': 'firewall rule',
                'verbose_name_plural': 'firewall rules',
                'db_table': 'cluster_firewall_rule',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='firewallrule',
            unique_together={('firewall', 'name')},
        ),
    ]
