# Generated by Django 2.2 on 2019-04-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0002_auto_20190406_2145'),
        ('firewall_rule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewallrule',
            name='firewalls',
            field=models.ManyToManyField(editable=False, related_name='firewallrule_relations', to='firewall.Firewall'),
        ),
    ]
