# Generated by Django 2.2 on 2019-04-07 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firewall_rule', '0002_firewallrule_firewalls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firewallrule',
            name='firewalls',
        ),
    ]
