# Generated by Django 3.2.5 on 2021-07-13 07:03

from django.db import migrations, models
import systems.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('config', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('provider_type', models.CharField(editable=False, max_length=128, null=True)),
                ('variables', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('state_config', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('email', models.CharField(max_length=255, null=True)),
                ('certificate_authority', models.CharField(max_length=255, null=True)),
                ('certificate_updated', models.DateTimeField(editable=False, null=True)),
                ('valid_days', models.IntegerField(default=60)),
                ('private_key', systems.models.fields.EncryptedDataField(null=True)),
                ('certificate', systems.models.fields.EncryptedDataField(null=True)),
                ('chain', systems.models.fields.EncryptedDataField(null=True)),
                ('fullchain', systems.models.fields.EncryptedDataField(null=True)),
                ('groups', models.ManyToManyField(related_name='domain_relations', to='group.Group')),
            ],
            options={
                'verbose_name': 'domain',
                'verbose_name_plural': 'domains',
                'db_table': 'cluster_domain',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
