# Generated by Django 2.2 on 2019-04-04 21:47

from django.db import migrations, models
import systems.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='certificate',
            field=systems.models.fields.EncryptedDataField(null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='certificate_authority',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='chain',
            field=systems.models.fields.EncryptedDataField(null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='private_key',
            field=systems.models.fields.EncryptedDataField(null=True),
        ),
    ]
