# Generated by Django 2.2 on 2019-04-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_auto_20190404_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='certificate_updated',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
