# Generated by Django 2.2 on 2019-04-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_domain_valid_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='groups',
            field=models.ManyToManyField(related_name='domain_relations', to='group.Group'),
        ),
    ]
