# Generated by Django 3.2.5 on 2021-07-13 07:03

from django.db import migrations, models
import django.db.models.deletion
import systems.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('load_balancer', '0001_initial'),
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadBalancerListener',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('config', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('provider_type', models.CharField(editable=False, max_length=128, null=True)),
                ('variables', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('state_config', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('port', models.IntegerField(null=True)),
                ('target_port', models.IntegerField(null=True)),
                ('health_check_path', models.CharField(default='/', max_length=255)),
                ('health_check_interval', models.IntegerField(default=30)),
                ('health_check_timeout', models.IntegerField(default=10)),
                ('healthy_status', systems.models.fields.CSVField(default='200')),
                ('healthy_threshold', models.IntegerField(default=3)),
                ('unhealthy_threshold', models.IntegerField(default=3)),
                ('server_groups', systems.models.fields.CSVField(null=True)),
                ('certificate', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loadbalancerlistener_relation', to='certificate.certificate')),
                ('load_balancer', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loadbalancerlistener_relation', to='load_balancer.loadbalancer')),
            ],
            options={
                'verbose_name': 'load balancer listener',
                'verbose_name_plural': 'load balancer listeners',
                'db_table': 'cluster_load_balancer_listener',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('load_balancer', 'name')},
            },
        ),
    ]
