# Generated by Django 2.2 on 2019-04-06 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('load_balancer_listener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadbalancerlistener',
            name='domain',
        ),
    ]
