# Generated by Django 3.0 on 2020-06-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_balancer_listener', '0002_remove_loadbalancerlistener_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadbalancerlistener',
            name='health_check_path',
            field=models.CharField(default='/', max_length=255),
        ),
    ]
